// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: generate/proto/services/localrpc/localrpc.proto

package localrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCompletionsRequest specifies which command and field to complete
type GetCompletionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command path, e.g. "pipeline tcp" or "exec"
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Flag name to complete (e.g. "listener"). Empty for positional args.
	Flag string `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	// Positional argument index (used when flag is empty)
	ArgIndex int32 `protobuf:"varint,3,opt,name=arg_index,json=argIndex,proto3" json:"arg_index,omitempty"`
	// Current user input for filtering
	Current string `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
	// Session context for session-aware completions
	SessionId     string `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletionsRequest) Reset() {
	*x = GetCompletionsRequest{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletionsRequest) ProtoMessage() {}

func (x *GetCompletionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletionsRequest.ProtoReflect.Descriptor instead.
func (*GetCompletionsRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{0}
}

func (x *GetCompletionsRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *GetCompletionsRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *GetCompletionsRequest) GetArgIndex() int32 {
	if x != nil {
		return x.ArgIndex
	}
	return 0
}

func (x *GetCompletionsRequest) GetCurrent() string {
	if x != nil {
		return x.Current
	}
	return ""
}

func (x *GetCompletionsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// CompletionItem represents a single completion candidate
type CompletionItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The completion value to insert
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Display text (may differ from value)
	Display string `protobuf:"bytes,2,opt,name=display,proto3" json:"display,omitempty"`
	// Description of this completion
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Category tag (e.g. "listener id", "session id", "pipeline")
	Tag           string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionItem) Reset() {
	*x = CompletionItem{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionItem) ProtoMessage() {}

func (x *CompletionItem) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionItem.ProtoReflect.Descriptor instead.
func (*CompletionItem) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{1}
}

func (x *CompletionItem) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CompletionItem) GetDisplay() string {
	if x != nil {
		return x.Display
	}
	return ""
}

func (x *CompletionItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompletionItem) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// GetCompletionsResponse contains completion results
type GetCompletionsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of completion candidates
	Items []*CompletionItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// Whether the operation was successful
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if completion failed
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompletionsResponse) Reset() {
	*x = GetCompletionsResponse{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompletionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompletionsResponse) ProtoMessage() {}

func (x *GetCompletionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompletionsResponse.ProtoReflect.Descriptor instead.
func (*GetCompletionsResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{2}
}

func (x *GetCompletionsResponse) GetItems() []*CompletionItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetCompletionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCompletionsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ExecuteCommandRequest contains the command to execute and optional session context
type ExecuteCommandRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The command to execute, exactly as you would type it in the console
	// Examples:
	// - "session --all" - List all sessions
	// - "use <session_id>" - Switch to a session
	// - "whoami" - Execute whoami in current session (requires active session)
	// - "ls" - List files in current directory (requires active session)
	Command string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	// Optional session ID to set as active context before execution
	// If not provided, uses the current active session
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteCommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ExecuteCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ExecuteCommandResponse contains the result of command execution
type ExecuteCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The output from the command execution
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// Error message if the command failed
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Whether the command executed successfully
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{4}
}

func (x *ExecuteCommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ExecuteLuaRequest contains the Lua script to execute and optional session context
type ExecuteLuaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Lua script code to execute
	// The script has access to:
	// - session: current session object
	// - session_id: current session ID
	// - console: console object
	// - All registered internal functions
	Script string `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	// Optional session ID to set as active context before execution
	// If provided, the session context will be switched before script execution
	// and restored after execution completes
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteLuaRequest) Reset() {
	*x = ExecuteLuaRequest{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteLuaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteLuaRequest) ProtoMessage() {}

func (x *ExecuteLuaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteLuaRequest.ProtoReflect.Descriptor instead.
func (*ExecuteLuaRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteLuaRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ExecuteLuaRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// ExecuteLuaResponse contains the result of Lua script execution
type ExecuteLuaResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The output/return value from the Lua script execution
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// Error message if the script failed
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Whether the script executed successfully
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteLuaResponse) Reset() {
	*x = ExecuteLuaResponse{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteLuaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteLuaResponse) ProtoMessage() {}

func (x *ExecuteLuaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteLuaResponse.ProtoReflect.Descriptor instead.
func (*ExecuteLuaResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteLuaResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *ExecuteLuaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteLuaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetHistoryRequest contains the task ID to query
type GetHistoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Task ID to retrieve history for
	TaskId uint32 `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Session ID context
	SessionId     string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryRequest) Reset() {
	*x = GetHistoryRequest{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryRequest) ProtoMessage() {}

func (x *GetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetHistoryRequest) GetTaskId() uint32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *GetHistoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// GetHistoryResponse contains the rendered history data
type GetHistoryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rendered output for the task
	Output string `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	// Error message if retrieval failed
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Whether the operation was successful
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoryResponse) Reset() {
	*x = GetHistoryResponse{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoryResponse) ProtoMessage() {}

func (x *GetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{8}
}

func (x *GetHistoryResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *GetHistoryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetHistoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetSchemasRequest contains the cobra group to query
type GetSchemasRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cobra command group to retrieve schemas for
	// Examples: "implant", "execute", "sys", "file", "pivot"
	// Required field
	Group         string `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemasRequest) Reset() {
	*x = GetSchemasRequest{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemasRequest) ProtoMessage() {}

func (x *GetSchemasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemasRequest.ProtoReflect.Descriptor instead.
func (*GetSchemasRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{9}
}

func (x *GetSchemasRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// GetSchemasResponse contains the JSON schemas for commands
type GetSchemasResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON string containing schemas for commands in the specified group
	// Format: { "group_name": { "command_name": schema } }
	SchemasJson string `protobuf:"bytes,1,opt,name=schemas_json,json=schemasJson,proto3" json:"schemas_json,omitempty"`
	// Error message if retrieval failed
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Whether the operation was successful
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchemasResponse) Reset() {
	*x = GetSchemasResponse{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchemasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchemasResponse) ProtoMessage() {}

func (x *GetSchemasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchemasResponse.ProtoReflect.Descriptor instead.
func (*GetSchemasResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{10}
}

func (x *GetSchemasResponse) GetSchemasJson() string {
	if x != nil {
		return x.SchemasJson
	}
	return ""
}

func (x *GetSchemasResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetSchemasResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetGroupsRequest contains the request for getting all groups
type GetGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsRequest) Reset() {
	*x = GetGroupsRequest{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsRequest) ProtoMessage() {}

func (x *GetGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupsRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{11}
}

// GetGroupsResponse contains information about all available groups
type GetGroupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of group ID to group title
	// Format: { "execute": "Execute", "sys": "System", "file": "File", ... }
	Groups map[string]string `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Error message if retrieval failed
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Whether the operation was successful
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupsResponse) Reset() {
	*x = GetGroupsResponse{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupsResponse) ProtoMessage() {}

func (x *GetGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupsResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{12}
}

func (x *GetGroupsResponse) GetGroups() map[string]string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetGroupsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetGroupsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// SearchCommandsRequest contains search parameters for command discovery
type SearchCommandsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full-text search query (FTS5 syntax supported: AND, OR, NOT, phrases)
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Optional group filter to narrow search scope
	// Examples: "implant", "execute", "sys", "file", "pivot"
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Optional session ID to scope search to commands available for that session
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Filter by result type: "command", "plugin", or "" for all
	TypeFilter string `protobuf:"bytes,4,opt,name=type_filter,json=typeFilter,proto3" json:"type_filter,omitempty"`
	// Maximum results to return (default 20)
	Limit         int32 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommandsRequest) Reset() {
	*x = SearchCommandsRequest{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommandsRequest) ProtoMessage() {}

func (x *SearchCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommandsRequest.ProtoReflect.Descriptor instead.
func (*SearchCommandsRequest) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{13}
}

func (x *SearchCommandsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchCommandsRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SearchCommandsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SearchCommandsRequest) GetTypeFilter() string {
	if x != nil {
		return x.TypeFilter
	}
	return ""
}

func (x *SearchCommandsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// CommandInfo contains a lightweight summary of a command
type CommandInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Command name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Command group ID
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Short description
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// ATT&CK technique ID (e.g., "T1033")
	Ttp string `protobuf:"bytes,4,opt,name=ttp,proto3" json:"ttp,omitempty"`
	// OPSEC safety rating (1-10, higher is safer)
	Opsec int32 `protobuf:"varint,5,opt,name=opsec,proto3" json:"opsec,omitempty"`
	// Usage line showing command syntax
	Usage string `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	// List of subcommand names
	Subcommands []string `protobuf:"bytes,7,rep,name=subcommands,proto3" json:"subcommands,omitempty"`
	// FTS5 highlighted snippet showing match context
	Snippet string `protobuf:"bytes,8,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// Command source: "builtin", "mal", "lua", "alias", "extension"
	Source string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	// FTS5 relevance rank (lower is better match)
	Rank          float64 `protobuf:"fixed64,10,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandInfo) Reset() {
	*x = CommandInfo{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfo) ProtoMessage() {}

func (x *CommandInfo) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfo.ProtoReflect.Descriptor instead.
func (*CommandInfo) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{14}
}

func (x *CommandInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CommandInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandInfo) GetTtp() string {
	if x != nil {
		return x.Ttp
	}
	return ""
}

func (x *CommandInfo) GetOpsec() int32 {
	if x != nil {
		return x.Opsec
	}
	return 0
}

func (x *CommandInfo) GetUsage() string {
	if x != nil {
		return x.Usage
	}
	return ""
}

func (x *CommandInfo) GetSubcommands() []string {
	if x != nil {
		return x.Subcommands
	}
	return nil
}

func (x *CommandInfo) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *CommandInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *CommandInfo) GetRank() float64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

// SearchCommandsResponse contains matching command summaries
type SearchCommandsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of matching commands
	Commands []*CommandInfo `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	// Error message if search failed
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Whether the operation was successful
	Success bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	// Total number of results found
	TotalCount    int32 `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCommandsResponse) Reset() {
	*x = SearchCommandsResponse{}
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCommandsResponse) ProtoMessage() {}

func (x *SearchCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generate_proto_services_localrpc_localrpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCommandsResponse.ProtoReflect.Descriptor instead.
func (*SearchCommandsResponse) Descriptor() ([]byte, []int) {
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP(), []int{15}
}

func (x *SearchCommandsResponse) GetCommands() []*CommandInfo {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *SearchCommandsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SearchCommandsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchCommandsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_generate_proto_services_localrpc_localrpc_proto protoreflect.FileDescriptor

const file_generate_proto_services_localrpc_localrpc_proto_rawDesc = "" +
	"\n" +
	"/generate/proto/services/localrpc/localrpc.proto\x12\x11services.localrpc\"\x9b\x01\n" +
	"\x15GetCompletionsRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\tR\x04flag\x12\x1b\n" +
	"\targ_index\x18\x03 \x01(\x05R\bargIndex\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\tR\acurrent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"t\n" +
	"\x0eCompletionItem\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\adisplay\x18\x02 \x01(\tR\adisplay\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\"\x81\x01\n" +
	"\x16GetCompletionsResponse\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.services.localrpc.CompletionItemR\x05items\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"P\n" +
	"\x15ExecuteCommandRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"`\n" +
	"\x16ExecuteCommandResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"J\n" +
	"\x11ExecuteLuaRequest\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\\\n" +
	"\x12ExecuteLuaResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"K\n" +
	"\x11GetHistoryRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\rR\x06taskId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\\\n" +
	"\x12GetHistoryResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\")\n" +
	"\x11GetSchemasRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\"g\n" +
	"\x12GetSchemasResponse\x12!\n" +
	"\fschemas_json\x18\x01 \x01(\tR\vschemasJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x12\n" +
	"\x10GetGroupsRequest\"\xc8\x01\n" +
	"\x11GetGroupsResponse\x12H\n" +
	"\x06groups\x18\x01 \x03(\v20.services.localrpc.GetGroupsResponse.GroupsEntryR\x06groups\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x1a9\n" +
	"\vGroupsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x99\x01\n" +
	"\x15SearchCommandsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vtype_filter\x18\x04 \x01(\tR\n" +
	"typeFilter\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"\xff\x01\n" +
	"\vCommandInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x10\n" +
	"\x03ttp\x18\x04 \x01(\tR\x03ttp\x12\x14\n" +
	"\x05opsec\x18\x05 \x01(\x05R\x05opsec\x12\x14\n" +
	"\x05usage\x18\x06 \x01(\tR\x05usage\x12 \n" +
	"\vsubcommands\x18\a \x03(\tR\vsubcommands\x12\x18\n" +
	"\asnippet\x18\b \x01(\tR\asnippet\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x12\n" +
	"\x04rank\x18\n" +
	" \x01(\x01R\x04rank\"\xa5\x01\n" +
	"\x16SearchCommandsResponse\x12:\n" +
	"\bcommands\x18\x01 \x03(\v2\x1e.services.localrpc.CommandInfoR\bcommands\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x05R\n" +
	"totalCount2\x96\x06\n" +
	"\x0eCommandService\x12e\n" +
	"\x0eExecuteCommand\x12(.services.localrpc.ExecuteCommandRequest\x1a).services.localrpc.ExecuteCommandResponse\x12Y\n" +
	"\n" +
	"ExecuteLua\x12$.services.localrpc.ExecuteLuaRequest\x1a%.services.localrpc.ExecuteLuaResponse\x12Y\n" +
	"\n" +
	"GetHistory\x12$.services.localrpc.GetHistoryRequest\x1a%.services.localrpc.GetHistoryResponse\x12Y\n" +
	"\n" +
	"GetSchemas\x12$.services.localrpc.GetSchemasRequest\x1a%.services.localrpc.GetSchemasResponse\x12V\n" +
	"\tGetGroups\x12#.services.localrpc.GetGroupsRequest\x1a$.services.localrpc.GetGroupsResponse\x12e\n" +
	"\x0eSearchCommands\x12(.services.localrpc.SearchCommandsRequest\x1a).services.localrpc.SearchCommandsResponse\x12f\n" +
	"\rStreamCommand\x12(.services.localrpc.ExecuteCommandRequest\x1a).services.localrpc.ExecuteCommandResponse0\x01\x12e\n" +
	"\x0eGetCompletions\x12(.services.localrpc.GetCompletionsRequest\x1a).services.localrpc.GetCompletionsResponseB9Z7github.com/chainreactors/IoM-go/proto/services/localrpcb\x06proto3"

var (
	file_generate_proto_services_localrpc_localrpc_proto_rawDescOnce sync.Once
	file_generate_proto_services_localrpc_localrpc_proto_rawDescData []byte
)

func file_generate_proto_services_localrpc_localrpc_proto_rawDescGZIP() []byte {
	file_generate_proto_services_localrpc_localrpc_proto_rawDescOnce.Do(func() {
		file_generate_proto_services_localrpc_localrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_proto_services_localrpc_localrpc_proto_rawDesc), len(file_generate_proto_services_localrpc_localrpc_proto_rawDesc)))
	})
	return file_generate_proto_services_localrpc_localrpc_proto_rawDescData
}

var file_generate_proto_services_localrpc_localrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_generate_proto_services_localrpc_localrpc_proto_goTypes = []any{
	(*GetCompletionsRequest)(nil),  // 0: services.localrpc.GetCompletionsRequest
	(*CompletionItem)(nil),         // 1: services.localrpc.CompletionItem
	(*GetCompletionsResponse)(nil), // 2: services.localrpc.GetCompletionsResponse
	(*ExecuteCommandRequest)(nil),  // 3: services.localrpc.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil), // 4: services.localrpc.ExecuteCommandResponse
	(*ExecuteLuaRequest)(nil),      // 5: services.localrpc.ExecuteLuaRequest
	(*ExecuteLuaResponse)(nil),     // 6: services.localrpc.ExecuteLuaResponse
	(*GetHistoryRequest)(nil),      // 7: services.localrpc.GetHistoryRequest
	(*GetHistoryResponse)(nil),     // 8: services.localrpc.GetHistoryResponse
	(*GetSchemasRequest)(nil),      // 9: services.localrpc.GetSchemasRequest
	(*GetSchemasResponse)(nil),     // 10: services.localrpc.GetSchemasResponse
	(*GetGroupsRequest)(nil),       // 11: services.localrpc.GetGroupsRequest
	(*GetGroupsResponse)(nil),      // 12: services.localrpc.GetGroupsResponse
	(*SearchCommandsRequest)(nil),  // 13: services.localrpc.SearchCommandsRequest
	(*CommandInfo)(nil),            // 14: services.localrpc.CommandInfo
	(*SearchCommandsResponse)(nil), // 15: services.localrpc.SearchCommandsResponse
	nil,                            // 16: services.localrpc.GetGroupsResponse.GroupsEntry
}
var file_generate_proto_services_localrpc_localrpc_proto_depIdxs = []int32{
	1,  // 0: services.localrpc.GetCompletionsResponse.items:type_name -> services.localrpc.CompletionItem
	16, // 1: services.localrpc.GetGroupsResponse.groups:type_name -> services.localrpc.GetGroupsResponse.GroupsEntry
	14, // 2: services.localrpc.SearchCommandsResponse.commands:type_name -> services.localrpc.CommandInfo
	3,  // 3: services.localrpc.CommandService.ExecuteCommand:input_type -> services.localrpc.ExecuteCommandRequest
	5,  // 4: services.localrpc.CommandService.ExecuteLua:input_type -> services.localrpc.ExecuteLuaRequest
	7,  // 5: services.localrpc.CommandService.GetHistory:input_type -> services.localrpc.GetHistoryRequest
	9,  // 6: services.localrpc.CommandService.GetSchemas:input_type -> services.localrpc.GetSchemasRequest
	11, // 7: services.localrpc.CommandService.GetGroups:input_type -> services.localrpc.GetGroupsRequest
	13, // 8: services.localrpc.CommandService.SearchCommands:input_type -> services.localrpc.SearchCommandsRequest
	3,  // 9: services.localrpc.CommandService.StreamCommand:input_type -> services.localrpc.ExecuteCommandRequest
	0,  // 10: services.localrpc.CommandService.GetCompletions:input_type -> services.localrpc.GetCompletionsRequest
	4,  // 11: services.localrpc.CommandService.ExecuteCommand:output_type -> services.localrpc.ExecuteCommandResponse
	6,  // 12: services.localrpc.CommandService.ExecuteLua:output_type -> services.localrpc.ExecuteLuaResponse
	8,  // 13: services.localrpc.CommandService.GetHistory:output_type -> services.localrpc.GetHistoryResponse
	10, // 14: services.localrpc.CommandService.GetSchemas:output_type -> services.localrpc.GetSchemasResponse
	12, // 15: services.localrpc.CommandService.GetGroups:output_type -> services.localrpc.GetGroupsResponse
	15, // 16: services.localrpc.CommandService.SearchCommands:output_type -> services.localrpc.SearchCommandsResponse
	4,  // 17: services.localrpc.CommandService.StreamCommand:output_type -> services.localrpc.ExecuteCommandResponse
	2,  // 18: services.localrpc.CommandService.GetCompletions:output_type -> services.localrpc.GetCompletionsResponse
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_generate_proto_services_localrpc_localrpc_proto_init() }
func file_generate_proto_services_localrpc_localrpc_proto_init() {
	if File_generate_proto_services_localrpc_localrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_proto_services_localrpc_localrpc_proto_rawDesc), len(file_generate_proto_services_localrpc_localrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_generate_proto_services_localrpc_localrpc_proto_goTypes,
		DependencyIndexes: file_generate_proto_services_localrpc_localrpc_proto_depIdxs,
		MessageInfos:      file_generate_proto_services_localrpc_localrpc_proto_msgTypes,
	}.Build()
	File_generate_proto_services_localrpc_localrpc_proto = out.File
	file_generate_proto_services_localrpc_localrpc_proto_goTypes = nil
	file_generate_proto_services_localrpc_localrpc_proto_depIdxs = nil
}
