// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: generate/proto/services/localrpc/localrpc.proto

package localrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommandService_ExecuteCommand_FullMethodName = "/services.localrpc.CommandService/ExecuteCommand"
	CommandService_ExecuteLua_FullMethodName     = "/services.localrpc.CommandService/ExecuteLua"
	CommandService_GetHistory_FullMethodName     = "/services.localrpc.CommandService/GetHistory"
	CommandService_GetSchemas_FullMethodName     = "/services.localrpc.CommandService/GetSchemas"
	CommandService_GetGroups_FullMethodName      = "/services.localrpc.CommandService/GetGroups"
	CommandService_SearchCommands_FullMethodName = "/services.localrpc.CommandService/SearchCommands"
	CommandService_StreamCommand_FullMethodName  = "/services.localrpc.CommandService/StreamCommand"
	CommandService_GetCompletions_FullMethodName = "/services.localrpc.CommandService/GetCompletions"
)

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommandService provides gRPC methods for executing commands and Lua scripts
// in the context of the Malice Network C2 client
type CommandServiceClient interface {
	// ExecuteCommand executes a client command in the specified session context
	// Commands are automatically routed to client menu or implant menu based on
	// whether there's an active session
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	// ExecuteLua executes a Lua script with access to internal functions and
	// the current session context
	ExecuteLua(ctx context.Context, in *ExecuteLuaRequest, opts ...grpc.CallOption) (*ExecuteLuaResponse, error)
	// GetHistory retrieves rendered history data for a specific task
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// GetSchemas retrieves JSON schemas for commands in specified cobra group
	// Returns schemas suitable for react-jsonschema-form rendering
	GetSchemas(ctx context.Context, in *GetSchemasRequest, opts ...grpc.CallOption) (*GetSchemasResponse, error)
	// GetGroups retrieves information about all available command groups
	GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsResponse, error)
	// SearchCommands searches for commands by name or description with fuzzy matching
	// Returns lightweight command summaries to avoid context pollution
	SearchCommands(ctx context.Context, in *SearchCommandsRequest, opts ...grpc.CallOption) (*SearchCommandsResponse, error)
	// StreamCommand executes a command and continuously streams back task event output.
	// Suitable for any command that produces persistent EventTaskDone events (e.g. tapping, poison).
	// The client cancels the context to stop the stream.
	StreamCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteCommandResponse], error)
	// GetCompletions returns dynamic completion values for a specific flag or positional argument.
	// Called by UI when user focuses on a field that has registered completions.
	GetCompletions(ctx context.Context, in *GetCompletionsRequest, opts ...grpc.CallOption) (*GetCompletionsResponse, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, CommandService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) ExecuteLua(ctx context.Context, in *ExecuteLuaRequest, opts ...grpc.CallOption) (*ExecuteLuaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteLuaResponse)
	err := c.cc.Invoke(ctx, CommandService_ExecuteLua_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, CommandService_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) GetSchemas(ctx context.Context, in *GetSchemasRequest, opts ...grpc.CallOption) (*GetSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemasResponse)
	err := c.cc.Invoke(ctx, CommandService_GetSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupsResponse)
	err := c.cc.Invoke(ctx, CommandService_GetGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SearchCommands(ctx context.Context, in *SearchCommandsRequest, opts ...grpc.CallOption) (*SearchCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchCommandsResponse)
	err := c.cc.Invoke(ctx, CommandService_SearchCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) StreamCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteCommandResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CommandService_ServiceDesc.Streams[0], CommandService_StreamCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteCommandRequest, ExecuteCommandResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_StreamCommandClient = grpc.ServerStreamingClient[ExecuteCommandResponse]

func (c *commandServiceClient) GetCompletions(ctx context.Context, in *GetCompletionsRequest, opts ...grpc.CallOption) (*GetCompletionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompletionsResponse)
	err := c.cc.Invoke(ctx, CommandService_GetCompletions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility.
//
// CommandService provides gRPC methods for executing commands and Lua scripts
// in the context of the Malice Network C2 client
type CommandServiceServer interface {
	// ExecuteCommand executes a client command in the specified session context
	// Commands are automatically routed to client menu or implant menu based on
	// whether there's an active session
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// ExecuteLua executes a Lua script with access to internal functions and
	// the current session context
	ExecuteLua(context.Context, *ExecuteLuaRequest) (*ExecuteLuaResponse, error)
	// GetHistory retrieves rendered history data for a specific task
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// GetSchemas retrieves JSON schemas for commands in specified cobra group
	// Returns schemas suitable for react-jsonschema-form rendering
	GetSchemas(context.Context, *GetSchemasRequest) (*GetSchemasResponse, error)
	// GetGroups retrieves information about all available command groups
	GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsResponse, error)
	// SearchCommands searches for commands by name or description with fuzzy matching
	// Returns lightweight command summaries to avoid context pollution
	SearchCommands(context.Context, *SearchCommandsRequest) (*SearchCommandsResponse, error)
	// StreamCommand executes a command and continuously streams back task event output.
	// Suitable for any command that produces persistent EventTaskDone events (e.g. tapping, poison).
	// The client cancels the context to stop the stream.
	StreamCommand(*ExecuteCommandRequest, grpc.ServerStreamingServer[ExecuteCommandResponse]) error
	// GetCompletions returns dynamic completion values for a specific flag or positional argument.
	// Called by UI when user focuses on a field that has registered completions.
	GetCompletions(context.Context, *GetCompletionsRequest) (*GetCompletionsResponse, error)
	mustEmbedUnimplementedCommandServiceServer()
}

// UnimplementedCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommandServiceServer struct{}

func (UnimplementedCommandServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedCommandServiceServer) ExecuteLua(context.Context, *ExecuteLuaRequest) (*ExecuteLuaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteLua not implemented")
}
func (UnimplementedCommandServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedCommandServiceServer) GetSchemas(context.Context, *GetSchemasRequest) (*GetSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchemas not implemented")
}
func (UnimplementedCommandServiceServer) GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroups not implemented")
}
func (UnimplementedCommandServiceServer) SearchCommands(context.Context, *SearchCommandsRequest) (*SearchCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCommands not implemented")
}
func (UnimplementedCommandServiceServer) StreamCommand(*ExecuteCommandRequest, grpc.ServerStreamingServer[ExecuteCommandResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamCommand not implemented")
}
func (UnimplementedCommandServiceServer) GetCompletions(context.Context, *GetCompletionsRequest) (*GetCompletionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompletions not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}
func (UnimplementedCommandServiceServer) testEmbeddedByValue()                        {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	// If the following call panics, it indicates UnimplementedCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_ExecuteLua_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteLuaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).ExecuteLua(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_ExecuteLua_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).ExecuteLua(ctx, req.(*ExecuteLuaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_GetSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetSchemas(ctx, req.(*GetSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetGroups(ctx, req.(*GetGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SearchCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SearchCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SearchCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SearchCommands(ctx, req.(*SearchCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_StreamCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServiceServer).StreamCommand(m, &grpc.GenericServerStream[ExecuteCommandRequest, ExecuteCommandResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CommandService_StreamCommandServer = grpc.ServerStreamingServer[ExecuteCommandResponse]

func _CommandService_GetCompletions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompletionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetCompletions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetCompletions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetCompletions(ctx, req.(*GetCompletionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.localrpc.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _CommandService_ExecuteCommand_Handler,
		},
		{
			MethodName: "ExecuteLua",
			Handler:    _CommandService_ExecuteLua_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _CommandService_GetHistory_Handler,
		},
		{
			MethodName: "GetSchemas",
			Handler:    _CommandService_GetSchemas_Handler,
		},
		{
			MethodName: "GetGroups",
			Handler:    _CommandService_GetGroups_Handler,
		},
		{
			MethodName: "SearchCommands",
			Handler:    _CommandService_SearchCommands_Handler,
		},
		{
			MethodName: "GetCompletions",
			Handler:    _CommandService_GetCompletions_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCommand",
			Handler:       _CommandService_StreamCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "generate/proto/services/localrpc/localrpc.proto",
}
