// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.0
// source: services/localrpc/localrpc.proto

package localrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CommandService_ExecuteCommand_FullMethodName = "/services.localrpc.CommandService/ExecuteCommand"
	CommandService_ExecuteLua_FullMethodName     = "/services.localrpc.CommandService/ExecuteLua"
	CommandService_GetHistory_FullMethodName     = "/services.localrpc.CommandService/GetHistory"
	CommandService_GetSchemas_FullMethodName     = "/services.localrpc.CommandService/GetSchemas"
	CommandService_GetGroups_FullMethodName      = "/services.localrpc.CommandService/GetGroups"
	CommandService_SearchCommands_FullMethodName = "/services.localrpc.CommandService/SearchCommands"
	CommandService_StreamCommand_FullMethodName  = "/services.localrpc.CommandService/StreamCommand"
)

// CommandServiceClient is the client API for CommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandServiceClient interface {
	// ExecuteCommand executes a client command in the specified session context
	// Commands are automatically routed to client menu or implant menu based on
	// whether there's an active session
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	// ExecuteLua executes a Lua script with access to internal functions and
	// the current session context
	ExecuteLua(ctx context.Context, in *ExecuteLuaRequest, opts ...grpc.CallOption) (*ExecuteLuaResponse, error)
	// GetHistory retrieves rendered history data for a specific task
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	// GetSchemas retrieves JSON schemas for commands in specified cobra group
	// Returns schemas suitable for react-jsonschema-form rendering
	GetSchemas(ctx context.Context, in *GetSchemasRequest, opts ...grpc.CallOption) (*GetSchemasResponse, error)
	// GetGroups retrieves information about all available command groups
	GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsResponse, error)
	// SearchCommands searches for commands by name or description with fuzzy matching
	// Returns lightweight command summaries to avoid context pollution
	SearchCommands(ctx context.Context, in *SearchCommandsRequest, opts ...grpc.CallOption) (*SearchCommandsResponse, error)
	// StreamCommand executes a command and continuously streams back task event output.
	// Suitable for any command that produces persistent EventTaskDone events (e.g. tapping, poison).
	// The client cancels the context to stop the stream.
	StreamCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (CommandService_StreamCommandClient, error)
}

type commandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandServiceClient(cc grpc.ClientConnInterface) CommandServiceClient {
	return &commandServiceClient{cc}
}

func (c *commandServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, CommandService_ExecuteCommand_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) ExecuteLua(ctx context.Context, in *ExecuteLuaRequest, opts ...grpc.CallOption) (*ExecuteLuaResponse, error) {
	out := new(ExecuteLuaResponse)
	err := c.cc.Invoke(ctx, CommandService_ExecuteLua_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, CommandService_GetHistory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) GetSchemas(ctx context.Context, in *GetSchemasRequest, opts ...grpc.CallOption) (*GetSchemasResponse, error) {
	out := new(GetSchemasResponse)
	err := c.cc.Invoke(ctx, CommandService_GetSchemas_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) GetGroups(ctx context.Context, in *GetGroupsRequest, opts ...grpc.CallOption) (*GetGroupsResponse, error) {
	out := new(GetGroupsResponse)
	err := c.cc.Invoke(ctx, CommandService_GetGroups_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) SearchCommands(ctx context.Context, in *SearchCommandsRequest, opts ...grpc.CallOption) (*SearchCommandsResponse, error) {
	out := new(SearchCommandsResponse)
	err := c.cc.Invoke(ctx, CommandService_SearchCommands_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServiceClient) StreamCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (CommandService_StreamCommandClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommandService_ServiceDesc.Streams[0], CommandService_StreamCommand_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &commandServiceStreamCommandClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CommandService_StreamCommandClient interface {
	Recv() (*ExecuteCommandResponse, error)
	grpc.ClientStream
}

type commandServiceStreamCommandClient struct {
	grpc.ClientStream
}

func (x *commandServiceStreamCommandClient) Recv() (*ExecuteCommandResponse, error) {
	m := new(ExecuteCommandResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CommandServiceServer is the server API for CommandService service.
// All implementations must embed UnimplementedCommandServiceServer
// for forward compatibility
type CommandServiceServer interface {
	// ExecuteCommand executes a client command in the specified session context
	// Commands are automatically routed to client menu or implant menu based on
	// whether there's an active session
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// ExecuteLua executes a Lua script with access to internal functions and
	// the current session context
	ExecuteLua(context.Context, *ExecuteLuaRequest) (*ExecuteLuaResponse, error)
	// GetHistory retrieves rendered history data for a specific task
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	// GetSchemas retrieves JSON schemas for commands in specified cobra group
	// Returns schemas suitable for react-jsonschema-form rendering
	GetSchemas(context.Context, *GetSchemasRequest) (*GetSchemasResponse, error)
	// GetGroups retrieves information about all available command groups
	GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsResponse, error)
	// SearchCommands searches for commands by name or description with fuzzy matching
	// Returns lightweight command summaries to avoid context pollution
	SearchCommands(context.Context, *SearchCommandsRequest) (*SearchCommandsResponse, error)
	// StreamCommand executes a command and continuously streams back task event output.
	// Suitable for any command that produces persistent EventTaskDone events (e.g. tapping, poison).
	// The client cancels the context to stop the stream.
	StreamCommand(*ExecuteCommandRequest, CommandService_StreamCommandServer) error
	mustEmbedUnimplementedCommandServiceServer()
}

// UnimplementedCommandServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCommandServiceServer struct {
}

func (UnimplementedCommandServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedCommandServiceServer) ExecuteLua(context.Context, *ExecuteLuaRequest) (*ExecuteLuaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteLua not implemented")
}
func (UnimplementedCommandServiceServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedCommandServiceServer) GetSchemas(context.Context, *GetSchemasRequest) (*GetSchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSchemas not implemented")
}
func (UnimplementedCommandServiceServer) GetGroups(context.Context, *GetGroupsRequest) (*GetGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroups not implemented")
}
func (UnimplementedCommandServiceServer) SearchCommands(context.Context, *SearchCommandsRequest) (*SearchCommandsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchCommands not implemented")
}
func (UnimplementedCommandServiceServer) StreamCommand(*ExecuteCommandRequest, CommandService_StreamCommandServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCommand not implemented")
}
func (UnimplementedCommandServiceServer) mustEmbedUnimplementedCommandServiceServer() {}

// UnsafeCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServiceServer will
// result in compilation errors.
type UnsafeCommandServiceServer interface {
	mustEmbedUnimplementedCommandServiceServer()
}

func RegisterCommandServiceServer(s grpc.ServiceRegistrar, srv CommandServiceServer) {
	s.RegisterService(&CommandService_ServiceDesc, srv)
}

func _CommandService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_ExecuteLua_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteLuaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).ExecuteLua(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_ExecuteLua_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).ExecuteLua(ctx, req.(*ExecuteLuaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_GetSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetSchemas(ctx, req.(*GetSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_GetGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).GetGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_GetGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).GetGroups(ctx, req.(*GetGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_SearchCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServiceServer).SearchCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommandService_SearchCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServiceServer).SearchCommands(ctx, req.(*SearchCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandService_StreamCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteCommandRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommandServiceServer).StreamCommand(m, &commandServiceStreamCommandServer{stream})
}

type CommandService_StreamCommandServer interface {
	Send(*ExecuteCommandResponse) error
	grpc.ServerStream
}

type commandServiceStreamCommandServer struct {
	grpc.ServerStream
}

func (x *commandServiceStreamCommandServer) Send(m *ExecuteCommandResponse) error {
	return x.ServerStream.SendMsg(m)
}

// CommandService_ServiceDesc is the grpc.ServiceDesc for CommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.localrpc.CommandService",
	HandlerType: (*CommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommand",
			Handler:    _CommandService_ExecuteCommand_Handler,
		},
		{
			MethodName: "ExecuteLua",
			Handler:    _CommandService_ExecuteLua_Handler,
		},
		{
			MethodName: "GetHistory",
			Handler:    _CommandService_GetHistory_Handler,
		},
		{
			MethodName: "GetSchemas",
			Handler:    _CommandService_GetSchemas_Handler,
		},
		{
			MethodName: "GetGroups",
			Handler:    _CommandService_GetGroups_Handler,
		},
		{
			MethodName: "SearchCommands",
			Handler:    _CommandService_SearchCommands_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCommand",
			Handler:       _CommandService_StreamCommand_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/localrpc/localrpc.proto",
}
